const TAG: any = [
  { value: 1, name: 'Action'},
  { value: 49, name: 'Adapted to Anime'},
  { value: 51, name: 'Adapted to Drama CD'},
  { value: 50, name: 'Adapted to Manga'},
  { value: 28, name: 'Adult'},
  { value: 2, name: 'Adventure'},
  { value: 52, name: 'Age Gap'},
  { value: 60, name: 'Boys Love'},
  { value: 54, name: 'Character Growth'},
  { value: 39, name: 'Chinese Novel'},
  { value: 3, name: 'Comedy'},
  { value: 43, name: 'Cooking'},
  { value: 56, name: 'Different Social Status'},
  { value: 4, name: 'Drama'},
  { value: 5, name: 'Ecchi'},
  { value: 40, name: 'English Novel'},
  { value: 6, name: 'Fantasy'},
  { value: 59, name: 'Female Protagonist'},
  { value: 45, name: 'Game'},
  { value: 7, name: 'Gender Bender'},
  { value: 8, name: 'Harem'},
  { value: 35, name: 'Historical'},
  { value: 9, name: 'Horror'},
  { value: 10, name: 'Incest'},
  { value: 30, name: 'Isekai'},
  { value: 33, name: 'Josei'},
  { value: 34, name: 'Korean Novel'},
  { value: 44, name: 'Magic'},
  { value: 37, name: 'Martial Arts'},
  { value: 27, name: 'Mature'},
  { value: 11, name: 'Mecha'},
  { value: 36, name: 'Military'},
  { value: 58, name: 'Misunderstanding'},
  { value: 12, name: 'Mystery'},
  { value: 32, name: 'Netorare'},
  { value: 38, name: 'One shot'},
  { value: 46, name: 'Otome Game'},
  { value: 23, name: 'Psychological'},
  { value: 47, name: 'Reverse Harem'},
  { value: 22, name: 'Romance'},
  { value: 13, name: 'School Life'},
  { value: 14, name: 'Science Fiction'},
  { value: 31, name: 'Seinen'},
  { value: 15, name: 'Shoujo'},
  { value: 16, name: 'Shoujo ai'},
  { value: 26, name: 'Shounen'},
  { value: 17, name: 'Shounen ai'},
  { value: 18, name: 'Slice of Life'},
  { value: 55, name: 'Slow Life'},
  { value: 19, name: 'Sports'},
  { value: 24, name: 'Super Power'},
  { value: 20, name: 'Supernatural'},
  { value: 25, name: 'Suspense'},
  { value: 21, name: 'Tragedy'},
  { value: 53, name: 'Wars'},
  { value: 29, name: 'Web Novel'},
  { value: 57, name: 'Workplace'},
  { value: 48, name: 'Yuri'},
];

const STORY_STATUS: any = {
  1: 'Đang tiến hành',
  2: 'Tạm ngưng',
  3: 'Đã hoàn thành'
}

const STORY_TYPE: any = {
  1: 'Truyện dịch',
  2: 'Truyện convert',
  3: 'Truyện sáng tác',
}

export { TAG, STORY_STATUS, STORY_TYPE }